when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        make_factory:
            default_namespace: 'App\Tests\TestHelpers\Factories\Entity'
            add_hints: false
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true

    services:
        App\Tests\TestHelpers\Factories\Entity\:
            resource: '%kernel.project_dir%/tests/TestHelpers/Factories/Entity/'
            autowire: true
            autoconfigure: true

when@test: *dev
